### ISSUE TITLE
How to embed the docx file to another one?

### ISSUE THREAD

**Issue by iris55** [unidoc/unioffice#313] opened 2019-07-31 07:38 UTC
## Description
Hi, 
I have a request to embed the docx file to another docx file. 
Do you have any plan to implement this? Thank you~

## Expected Behavior
Embed the docx file as shown in the figure.
![image](https://user-images.githubusercontent.com/49423902/62192679-9d830d80-b3a8-11e9-8d35-2e42e4637ebf.png)

## Actual Behavior
Not supported.

**Comment by gunnsth** [comment] 2019-11-18 22:24
Looks like a duplicate of #277 which is more specific, i.e. support embedding another docx file via subDocument relation.

**Closed by gunnsth** 2019-11-18 22:24 UTC
Labels: feature
