### ISSUE TITLE
Creating a table in a document cannot really merge cells

### ISSUE THREAD

**Issue by leavky** [unidoc/unioffice#418] opened 2020-07-04 14:42 UTC
## Description
Creating a table in a document cannot really merge cells，Open the created document with Word365, Adjust it a little ,The merged cells are separated。
unioffice\_examples\document\tables\main.go
## Expected Behavior
merge cells
## Actual Behavior
cannot really merge cells

![image](https://user-images.githubusercontent.com/46547390/86514851-78640e00-be47-11ea-9a9f-d5a60000b064.png)

**Comment by gunnsth** [comment] 2020-10-08 22:39
@leavky Please attach the minimum code and files needed to reproduce the issue so we can investigate.

**Comment by gunnsth** [comment] 2021-06-03 20:51
The output of the example looks like
![image](https://user-images.githubusercontent.com/50777/120710118-48851680-c4ad-11eb-8de9-120e4cfed579.png)
can see that the row is spanning multiple columns.... Of course that can be changed by editing in Word, just like anything else can be changed in word...

Closing.  Please clarify if we are misunderstanding something and reopen.

**Closed by gunnsth** 2021-06-03 20:51 UTC
Labels: document, pending

**Comment by yansuan** [comment] 2022-01-26 03:24
**I also had the same problem.**

![image](https://user-images.githubusercontent.com/18570764/151098715-d6d85d56-af1e-4522-a681-f0320c3a3342.png)

`
func createTable() {
	doc := document.New()
	defer doc.Close()

	table := doc.AddTable()
	// 4 inches wide
	table.Properties().SetWidth(4 * measurement.Inch)
	borders := table.Properties().Borders()
	// thin borders
	borders.SetAll(wml.ST_BorderSingle, color.Auto, measurement.Zero)

	row := table.AddRow()
	cell := row.AddCell()
	// column span / merged cells
	cell.Properties().SetColumnSpan(2)

	run := cell.AddParagraph().AddRun()
	run.AddText("Cells can span multiple columns")

	row = table.AddRow()
	cell = row.AddCell()
	cell.Properties().SetVerticalMerge(wml.ST_MergeRestart)
	cell.AddParagraph().AddRun().AddText("Vertical Merge")
	row.AddCell().AddParagraph().AddRun().AddText("")

	row = table.AddRow()
	cell = row.AddCell()
	cell.Properties().SetVerticalMerge(wml.ST_MergeContinue)
	cell.AddParagraph().AddRun().AddText("Vertical Merge 2")
	row.AddCell().AddParagraph().AddRun().AddText("")

	row = table.AddRow()
	row.AddCell().AddParagraph().AddRun().AddText("Street Address")
	row.AddCell().AddParagraph().AddRun().AddText("111 Country Road")

	doc.AddParagraph()

	if err := doc.Validate(); err != nil {
		log.Fatalf("error during validation: %s", err)
	}
	doc.SaveToFile("table.docx")
}`
