### ISSUE TITLE
SetHeader Function Change Word Line Spacing

### ISSUE THREAD

**Issue by yeezyi** [unidoc/unioffice#524] opened 2024-10-22 06:58 UTC
## Description
after use SetHeader Func, The Paragraph LineSpacing was be changed, the verticalAlignment of Paragraph change to top
## Expected Behavior
<img width="602" alt="image" src="https://github.com/user-attachments/assets/5a244406-c367-4ef1-85e4-e4e152a1bffe">

## Actual Behavior
<img width="653" alt="image" src="https://github.com/user-attachments/assets/4dc5d6d8-527f-4d67-8072-17a88ea1d004">

Please include a reproducible code snippet or document attachment that
demonstrates the issue.

```go
func main() {
	doc := document.New()
	defer doc.Close()

	img, err := common.ImageFromFile("gophercolor.png")
	if err != nil {
		log.Fatalf("unable to create image: %s", err)
	}

	hdr := doc.AddHeader()
	iref, err := hdr.AddImage(img)
	if err != nil {
		log.Fatalf("unable to to add image to document: %s", err)
	}

	para := hdr.AddParagraph()

	imgInl, _ := para.AddRun().AddDrawingInline(iref)
	imgInl.SetSize(1*measurement.Inch, 1*measurement.Inch)

        // -----the only different is use or not the follow line code -----
	// doc.BodySection().SetHeader(hdr, wml.ST_HdrFtrDefault)


	text := `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin lobortis, lectus dictum feugiat tempus, sem neque finibus enim, sed eleifend sem nunc ac diam. Vestibulum tempus sagittis elementum`

	para = doc.AddParagraph()
	para.SetLineSpacing(30, wml.ST_LineSpacingRuleAuto)
	
	run := para.AddRun()
	run.Properties().SetSize(18)
	run.AddText(text)

	para.Properties().VerticalAlignment()

	doc.SaveToFile("header-footer.docx")
}
```

**Comment by ipod4g** [comment] 2024-10-30 20:02
@yeezyi Thank you for reaching out about this issue. We'll review it and provide an update soon.

**Comment by anovik** [comment] 2024-11-12 09:30
@yeezyi I've tested both cases (with header and without header) with the latest UniOffice version (v.1.37.0) and behavior is the same, line spacing and alignment are the same for these two cases. 

Could you please make sure you are using the latest version of UniOffice?

**Comment by anovik** [comment] 2024-11-22 06:50
@yeezyi We are closing your issue since we can't reproduce it with the latest versions of UniOffice. If you have additional information or a problem, feel free to re-open this issue or post a new one.

**Closed by anovik** 2024-11-22 06:50 UTC
