### ISSUE TITLE
Placeholders are being split

### ISSUE THREAD

**Issue by robtrooper** [unidoc/unioffice#394] opened 2020-05-15 12:19 UTC
## Description
Using edit-document example code but with own template.docx. Placeholders are not being respected.

## Expected Behavior
case "xxaddressxx":

will then catch my xxaddressxx placeholder and i can perform my function on that.

## Actual Behavior

Placeholders are being split and breaks the switch logic.
using
case "xxaddressxx":
results in 
'not modifying xx'
'not modifying address'
'not modifying xx'

Please include a reproducible code snippet or document attachment that
demonstrates the issue.

docx has 'xxaddressxx' in the body of the document.

Go code has this is switch statement
			case "xxaddressxx":
				r.ClearContent()
				r.AddText("Resident address")

Edited to add. Added the wrong title. Changed now.

**Comment by gunnsth** [comment] 2020-06-01 14:12
@robtrooper Can you please include your input and output files?  What unipdf version did you use?  Would be good to have screenshots to with markups to clarify what the problem is.

**Comment by gunnsth** [comment] 2020-10-11 14:07
Closing as we do not have a way to reproduce this.  Please reopen with minimum code and files needed to reproduce the issue if it comes up again.

**Closed by gunnsth** 2020-10-11 14:07 UTC
Labels: document, pending
