### ISSUE TITLE
Problem with adding content or modifying header in docx file

### ISSUE THREAD

**Issue by mytea003** [unidoc/unioffice#405] opened 2020-06-14 13:59 UTC
## Description
I wanted to add what I wanted in the header and set the location, but this was too difficult. There are no relevant instances.

You can add content to the header, but there are two problems:

1. Cannot add to the existing content;

2. After adding, the watermark disappears.

## Expected Behavior
![tesa1](https://user-images.githubusercontent.com/45747375/84595411-4ab02880-ae8a-11ea-986d-c9277dfe81dc.jpg)

Have a watermark.
## Actual Behavior
![tesa2](https://user-images.githubusercontent.com/45747375/84595115-d9bc4100-ae88-11ea-91ed-b171ea46a358.jpg)

 code：
doc, err := document.Open("abc.docx")
	if err != nil {
		log.Fatalf("err: %s", err)
	}
hdr := doc.AddHeader()
	para := hdr.AddParagraph()
	para.Properties().AddTabStop(6*measurement.Inch, wml.ST_TabJcRight, wml.ST_TabTlcUnset)
	run := para.AddRun()
	run.AddTab()
	run.AddText(Timec)
	run.Properties().SetBold(true)
	run.Properties().SetSize(8)
	run.Properties().SetColor(color.Black)
	doc.BodySection().SetHeader(hdr, wml.ST_HdrFtrUnset)

**Comment by gunnsth** [comment] 2020-06-30 16:00
@mytea003 Can you please provide all the files so that the case can be reproduced?

**Comment by gunnsth** [comment] 2020-06-30 19:30
Related or duplicate of #346

**Comment by mytea003** [comment] 2020-07-01 07:27
[testMod.zip](https://github.com/unidoc/unioffice/files/4856311/testMod.zip)

**Comment by mytea003** [comment] 2020-07-01 07:28
> @mytea003 Can you please provide all the files so that the case can be reproduced?

I have uploaded the file.

**Closed** 2020-11-09 12:17 UTC
Labels: document, pending, repro
